# Generated by Django 5.2.2 on 2025-06-06 03:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos_cadastro/', verbose_name='Foto de perfil')),
                ('nome', models.CharField(help_text='Digite o nome completo', max_length=100, verbose_name='Nome completo')),
                ('telefone', models.CharField(help_text='Formato: (XX) XXXXX-XXXX', max_length=15, unique=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, default='', max_length=200, verbose_name='Endereço Completo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('obs', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da presença')),
                ('obs', models.CharField(blank=True, default='', max_length=100, verbose_name='Observações')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_presenca', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Registro de presença',
                'verbose_name_plural': 'Registros de presença',
                'ordering': ['-dia', 'pessoa'],
                'unique_together': {('pessoa', 'dia')},
            },
        ),
    ]
