# Generated by Django 5.2.2 on 2025-06-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presenca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='batizado',
            field=models.IntegerField(choices=[(0, 'Não Batizado'), (1, 'Adventista'), (2, 'Outros')], default=2),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='endereco',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Endereço Completo'),
        ),
    ]
