# Generated by Django 5.2.2 on 2025-06-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presenca', '0002_pessoas_batizado_alter_pessoas_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='batizado',
            field=models.IntegerField(choices=[(0, 'Não Informado'), (1, 'Adventista'), (2, 'Outros'), (3, 'Não Batizado')], default=2),
        ),
    ]
